# PRTG Creation Tool v5 config (YAML)

prtg:
  baseUrl: "https://prtg.example.com:1616"    # with or without /api/v2
  apiKey: ""                                   # leave blank to use env: PRTG_API_KEY
  classicBaseUrl: "https://prtg.example.com:8443/"
  classicUser: ""
  classicPasshash: ""
  skipCertCheck: true

logging:
  logPath: "C:\\PRTG\\logs"
  verbose: true
  jsonSummaryPath: "C:\\PRTG\\logs\\run-summary.json"

defaults:
  parentGroupId: "2372"
  sensorType: "ping"         # only 'ping' supported in v5
  scanAfterCreate: true

csv:
  path: ".\\prtg-import.csv"
  columns:
    deviceName: "DeviceName"
    ip: "IP"
    groupId: "GroupId"
    groupName: "GroupName"
    parentGroupId: "ParentGroupId"
    groupPath: "GroupPath"

behavior:
  whatIf: false
  parallel: false
  maxConcurrency: 6
  retry:
    attempts: 2
    backoffSeconds: 2
